language: java

services:
  - docker

env:
  - NB_PLAYERS=6 NB_GAMES=2

jdk:
  - openjdk11

install:
  - cd ./7Wonders
  - mvn install -DskipTests

cache:
  directories:
    - $HOME/.m2

before_script:
  - docker ps -a -q
  - docker build java-server -t malta:server
  - docker build java-engine -t malta:engine
  - docker build java-player -t malta:player
  - docker images

script:
  - mvn test
  - docker run -d --rm -p 8080:8080 --name "serverIT" malta:server
  #- sleep 10 && docker run -d --rm -e ENGINE_IP="172.17.0.1" -e PORT="8092" -e TYPE="true" -p 8092:8092 --name "playerIT" malta:player &
  - mvn failsafe:integration-test
  - docker stop "serverIT"
  #- docker stop "playerIT"
  - docker-compose up --scale player=$NB_PLAYERS --force-recreate
  - docker-compose rm -f
  - docker rmi malta:server malta:engine malta:player
