language: java

services:
  - docker

jdk:
  - openjdk11

install:
  - cd ./7Wonders
  - mvn install -DskipTests

cache:
  directories:
    - $HOME/.m2

before_script:
  - docker ps -a -q
  - docker build java-server -t malta:server
  - docker build java-engine -t malta:engine
  - docker build java-player -t malta:player
  - docker images

script:
  - mvn test
  - docker-compose up --scale player=3 --force-recreate
  - docker-compose rm -f
  - docker rmi malta:server malta:engine malta:player
