language: java

services:
  - docker

jdk:
  - openjdk11

install:
  - cd ./7Wonders
  - mvn install -DskipTests

cache:
  directories:
    - $HOME/.m2

before_script:
  - docker ps -a -q
  - docker build java-server -t malta:server
  - docker build java-engine -t malta:engine
  - docker build java-player -t malta:player
  - docker images

script:
  - mvn test
  - docker run -d malta:server  &
 # - sleep 10 && docker run -d -e ENGINE_IP="172.17.0.1" -e PORT="8092" -e TYPE="true" -p 8092:8092 malta:player --name "player1" &
  - mvn failsafe:integration-test
  - docker-compose up --scale player=3 --force-recreate
  - docker-compose rm -f
  - docker rmi malta:server malta:engine malta:player
