language: java

services:
  - docker

env:
  - NB_PLAYERS=6 NB_GAMES=2

jdk:
  - openjdk11

install:
  - cd ./7Wonders
  - mvn install -DskipTests

cache:
  directories:
    - $HOME/.m2

before_script:
  - docker ps -a -q
  - docker build java-server -t malta:server
  - docker build java-engine -t malta:engine
  - docker build java-player -t malta:player
  - docker images

script:
  - mvn test
  - docker run -d --rm -p 8080:8080 --name "serverIT" malta:server
  #- docker run -d --rm -p 8081:8081 --name "engineIT" malta:engine
  #- sleep 10
  #- sleep 5 && docker run -d --rm -e ENGINE_IP="127.0.0.1" -e PORT="8092" -e TEST="true" -p 8092:8092 --name "playerIT1" malta:player &
  #- docker run -d --rm -e ENGINE_IP="172.17.0.1" -e PORT="8093" -e TEST="true" -p 8093:8093 --name "playerIT2" malta:player &
  #- docker run -d --rm -e ENGINE_IP="172.17.0.1" -e PORT="8094" -e TEST="true" -p 8094:8094 --name "playerIT3" malta:player &
  - mvn failsafe:integration-test
  - docker stop "serverIT" #"engineIT" #"playerIT1" "playerIT2" "playerIT3"
  #- docker-compose up --scale player=$NB_PLAYERS --force-recreate
  - docker-compose rm -f
  - docker rmi malta:server malta:engine malta:player

#mvn failsafe:integration-test -Dit.test=player.PlayerControllerITCase
