language: java

services:
  - docker

jdk:
  - openjdk11
  
#install:
#  - cd ./7Wonders
#  - mvn clean
#  - mvn install
#  - cd ./java-engine
#  - mvn exec:java@game3p
#  - cd ..

install:
  - cd ./7Wonders
  - mvn install -DskipTests

cache:
  directories:
    - $HOME/.m2

before_script:
  - docker ps -a -q
  - docker build java-server -t malta:server
  - docker build java-engine -t malta:engine
  - docker images

script:
  - mvn test
  #- SUBNET=172.28.0.0/16 IP=172.19.0.8 docker-compose up --force-recreate
  - docker-compose up
  - docker rm malta:engine
  - docker rm malta:server
  - docker ps -a -q
  - docker rmi malta:server