version: '3.7'

services:

  server:
    image: malta:server
    container_name: java-server
    networks:
      testing_net:
        ipv4_address: 172.28.0.253

  engine:
    image: malta:engine
    container_name: java-engine
    environment:
      - SERVER_IP=172.28.0.253
    depends_on:
      - server
    networks:
      testing_net:
        ipv4_address: 172.28.0.10

  player:
    image: malta:player
    environment:
      - ENGINE_IP=172.28.0.10
      - PORT=8080
      - TEST=false
    depends_on:
      - engine
    networks:
      testing_net:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

