version: '3'

services:

  server:
    image: malta:server
    container_name: java-server
    networks:
      testing_net:
        ipv4_address: 172.28.0.253

  #  player:
#    image: malta:player
#   container_name: java-player
#   networks:
#     testing_net:
#       ipv4_address: 172.28.0.253

  engine:
    image: malta:engine
    container_name: java-engine
    environment:
      - SERVER_IP=172.28.0.253
    depends_on:
      - server
    networks:
      testing_net:
      # ipv4_address: 172.28.0.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
